version: 2.1

defaults: &defaults
  docker:
    - image: greenpeaceinternational/p4-builder:latest

job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: test-venus
    CONTAINER_PREFIX: planet4-test-venus
    WP_DB_NAME_PREFIX: planet4-test-venus_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-test-venus
    NEWRELIC_APPNAME: P4 test-venus Development
    WP_DB_NAME: planet4-test-venus_wordpress_develop
    WP_STATELESS_BUCKET: planet4-test-venus-stateless-develop

job_definitions:
  build_steps: &build_steps
    working_directory: ~/
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - composer-v5-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
            - composer-v5-{{ .Branch }}-{{ .Revision }}
            - composer-v5-{{ .Branch }}
            - composer-v5
      - run: |
          if [[ -d source/cache ]]; then ls -al source/cache; fi
      - run: activate-gcloud-account.sh
      - run: mkdir -p /tmp/workspace/var
      - run: mkdir -p /tmp/workspace/src
      - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: make
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Build" notify-job-failure.sh
      - save_cache:
          key: composer-v5-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
          paths:
            - source/cache
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
            - src

  test_steps: &test_steps
    working_directory: ~/project
    docker:
      - image: gcr.io/planet-4-151612/p4-codeception:build-12
      - name: selenium
        image: selenium/standalone-chrome-debug:3.141.59-oxygen
    steps:
      - checkout
      - run: if [ ! -d "tests" ] || [ ! "$(ls -A tests)" ]; then circleci-agent step halt; fi
      - run: dockerize -wait tcp://selenium:4444
      - run: codeceptionify.sh .
      - run: codecept run --xml=junit.xml --html
      - run:
          name: Copy test artifacts
          when: always
          command: |
            mkdir -p /tmp/artifacts
            cp -r codeception/_output/. /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  deploy_steps: &deploy_steps
    working_directory: ~/
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: activate-gcloud-account.sh
      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make -j2 deploy

  backstop_history_steps: &backstop_history_steps
    docker:
      - image: greenpeaceinternational/planet4-backstop:latest
    working_directory: /src
    steps:
      - run: ./checkout.sh
      - run: ./mergescenarios.sh
      - run: mkdir /app/ -p
      - run: ./makehistory.sh
      - store_artifacts:
          path: /app/backstop_data
      - persist_to_workspace:
          root: /app
          paths:
            - backstop_data

  backstop_compare_steps: &backstop_compare_steps
    docker:
      - image: greenpeaceinternational/planet4-backstop:latest
    working_directory: /src
    steps:
      - run: ./checkout.sh
      - run: ./mergescenarios.sh
      - run: mkdir /app/ -p
      - attach_workspace:
          at: /app
      - run: ./makecomparison.sh
      - store_artifacts:
          path: /app/backstop_data


jobs:
  build-branch:
    <<: *defaults
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *build_steps

  test-develop:
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *test_steps

  deploy-develop:
    <<: *defaults
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *deploy_steps

  backstop-history-develop:
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *backstop_history_steps

  backstop-compare-develop:
    environment:
      <<: *common_environment
      <<: *develop_environment
    <<: *backstop_compare_steps


workflow_definitions:
  develop_common: &develop_common
    context: org-global
    filters:
      branches:
        only: develop

workflows:
  version: 2
  develop:
    jobs:
      - backstop-history-develop:
          <<: *develop_common
      - build-branch:
          <<: *develop_common
          requires:
            - backstop-history-develop
      - deploy-develop:
          <<: *develop_common
          requires:
            - build-branch
      - test-develop:
          <<: *develop_common
          requires:
            - deploy-develop
      - backstop-compare-develop:
          <<: *develop_common
          requires:
            - deploy-develop
